channels:
- uvcdat
- !!python/unicode 'defaults'
dependencies:
- uvcdat::cdms2
- uvcdat::vtk
- ffmpeg
- uvcdat::dv3d
- uvcdat::cdat_info
- uvcdat::genutil
- uvcdat::cdutil
- uvcdat::unidata
- requests
- uvcdat::vcsaddons
